default: &default
  site_modules:
    -
      name: Gobierto Development
      namespace: GobiertoDevelopment
    -
      name: Gobierto Budgets
      namespace: GobiertoBudgets
  dns_config:
    cname_record_target: site.gobierto.dev
    a_record_target: 222.111.222.11

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
